// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoWorkServer.Context;

#nullable disable

namespace TodoWorkServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TodoWorkServer.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Work")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Work")
                        .IsUnique();

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCompleted = false,
                            Work = "Get up"
                        },
                        new
                        {
                            Id = 2,
                            IsCompleted = false,
                            Work = "Work lesson"
                        },
                        new
                        {
                            Id = 3,
                            IsCompleted = false,
                            Work = "Go home"
                        },
                        new
                        {
                            Id = 4,
                            IsCompleted = false,
                            Work = "Take a shower"
                        },
                        new
                        {
                            Id = 5,
                            IsCompleted = false,
                            Work = "Get sleep"
                        },
                        new
                        {
                            Id = 6,
                            IsCompleted = true,
                            Work = "Check your e-mail"
                        },
                        new
                        {
                            Id = 7,
                            IsCompleted = true,
                            Work = "Brush teeth"
                        },
                        new
                        {
                            Id = 8,
                            IsCompleted = true,
                            Work = "Get to work"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
